# Generated by Django 5.2 on 2025-04-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0003_reviewproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
