# Generated by Django 5.2 on 2025-05-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
