# Generated by Django 5.2 on 2025-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0010_storeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='telegram_first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='telegram_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='telegram_last_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
