services:
  fastapi:
    build: .
    image: fastapi:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/backend/backend_fastAPI/
    ports:
      - "8000:8000"
    networks:
      main:
        ipv4_address: 172.22.0.7

networks:
  main:
    external: true


