version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/backend/django/
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://tg:tg@host.docker.internal:5432/tg_store

