# Generated by Django 5.2 on 2025-04-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_product', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipment', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField()),
                ('price', models.IntegerField()),
                ('cooling_power', models.FloatField()),
                ('heating_power', models.FloatField()),
                ('working_area', models.FloatField()),
                ('sound_level', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mini_app.brand')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mini_app.country')),
                ('group_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mini_app.subcategoryproduct')),
                ('type_equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mini_app.typeequipment')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_app.product')),
            ],
        ),
    ]
