# Generated by Django 5.2 on 2025-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0004_remove_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_main_menu',
            field=models.BooleanField(default=False),
        ),
    ]
