# Generated by Django 5.2 on 2025-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0005_product_view_main_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='article/', verbose_name='Изображение статьи')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('show_counter', models.IntegerField(null=True, verbose_name='Счетчик показов статьи')),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Изображение'),
        ),
    ]
