services:
  meilisearch_store_services:
    build: .
    command: python meilisearch_store/test.py
    volumes:
      - .:/usr/backend/service_meilisearch
    networks:
      - main
networks:
  main:
    external: true
