services:
  package:
    image: node:18
    tty: true
    stdin_open: true
    working_dir: /home/package
    command: "yarn run playground:dev"
    environment:
      - MEILISEARCH_HOST=http://localhost:7700
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ./:/home/package
    ports:
      - "1337:1337"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true